# Generated by Django 5.1.2 on 2024-11-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
